{{- if .Values.autoscaling.frontend.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: {{ .Values.autoscaling.frontend.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.frontend.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaling.frontend.targetCPUUtilizationPercentage }}

---
{{- end }}
{{- if .Values.autoscaling.backend.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: {{ .Values.autoscaling.backend.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.backend.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaling.frontend.targetCPUUtilizationPercentage }}
---
{{- end }}

